networks:
 northwindnetwork:
  driver: bridge

name: northwindapp

services:
  northwindapp:
    build:
      dockerfile: Northwind.Application/Dockerfile
    container_name: northwindapp-container
    networks: 
        - northwindnetwork

  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Haemorr_8421
    container_name: sql-server-container
    ports: 
        - 8082:1433
    networks: 
        - northwindnetwork
