version: '3.4'

networks:
 dev:
  driver: bridge

services:
  northwindapp:
    image: ${DOCKER_REGISTRY-}northwindapp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: northwindapp-container
    ports:
        - 8080:80
        - 8081:443
    environment: 
        - ASPNETCORE_URLS=https://+;http://+
    networks: 
        - dev

  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Haemorr_8421
    container_name: sql-server-container
    ports: 
        - 8082:1433
    networks: 
        - dev
